### ISSUE TITLE
feature proposal: make config optional

### ISSUE THREAD

**Issue by steveej** [isbecker/treefmt-vscode#3]
### issue

this would introduce compatibility with a wrapped treefmt binary that already encodes a `--config /nix/store/path`.

e.g. using this as a formatter seems convenient to me:

```nix
    inputs.treefmt-nix.lib.mkWrapper pkgs {
      # Used to find the project root
      projectRootFile = ".git/config";
      programs.nixfmt.enable = true;
    };
```

the wrapper binary `treefmt` ends with

```bash
exec /nix/store/m9q4afy31dshqb47047pghb1f4jr6fxf-treefmt-0.6.1/bin/treefmt --config-file /nix/store/ccr7krsq3grwsli2a5z206ypwdxz5ax5-treefmt.toml "$@" --tree-root "$tree_root"
```

for  treefmt v1,
when this is called by the extension it ends up with an error due to duplicate `--config` argument:

> Error running treefmt-nix: error: the argument '--config-file <CONFIG_FILE>' cannot be used multiple times Usage: treefmt [OPTIONS] [PATHS]... For more information, try '--help'.

for treevmt v2 it's not an error, and on first try treevmt v2 uses the last occurrence of `--config-file`, thus whatever happens to be in the repository.

### proposal

add an extension setting that indicates skipping of config creation and omitting the `--config <..>` argument.

**Comment by isbecker** [comment]
Hi @steveej, can you please let me know what version of the extension you have installed?

Thanks!

I hope that the issue you're facing may have been addressed in the latest 2.1.0 release. The change below, you can see that it only adds the `--config` when the option is set in the vscode settings for the extension.

https://github.com/isbecker/treefmt-vscode/blob/8a9369eb86ff2760b5825d386e68601100f1a050/src/extension.ts#L74-L79

**Comment by steveej** [comment]
thanks for the response @isbecker.

i just updated to v2.1.0. after removing the `treefmt.toml` and setting `"treefmt.config": null` explicitly i'm still seeing this notification when running treefmt in vscodium:

> treefmt.toml not found. Would you like to create treefmt.toml?

IIUC [this code correctly](https://github.com/isbecker/treefmt-vscode/blob/8a9369eb86ff2760b5825d386e68601100f1a050/src/extension.ts#L64-L70) it always returns early if the config hasn't existed when the call happened.

**Comment by isbecker** [comment]
@steveej thanks for the additional information and context, I will look into a fix for this behavior.

**Comment by andrea11** [comment]
Hi @steveej, sorry to comment here, but did you succeed to configure this plugin to use the store config? If so, can you detailed a bit how?

**Comment by steveej** [comment]
@hackardoX 

> Hi [@steveej](https://github.com/steveej), sorry for commenting in this closed conversation. Did you succeed to configure this plugin to use the store config? If so, can you detailed a bit how?

yes. i've found it necessary to define an empty config string in the settings to get the desired behavior:

```json
  "treefmt.command": "treefmt",
  "treefmt.config": ""
```
